# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # JVM max heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: chmod +x ./gradlew
      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - save_cache:
          paths:
            - ./gradle/wrapper
          key: v1-dependencies-{{ checksum "gradlew" }}

      - run: ./gradlew test
      - run: ./gradlew assemble

      # copy to destination
      - run: cp build/libs/Neutron-*.jar build/libs/final-plugin.jar

      # store artifact
      - store_artifacts:
          path: build/libs/final-plugin.jar
          destination: Neutron_N3FS.jar