name: Deploy to Bintray

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          mavenUrl: "https://api.bintray.com/maven/md678685/n3fs/neutron-n3fs/;publish=1"
          mavenUsername: md678685
          mavenPassword: ${{ secrets.BINTRAY_TOKEN }}
        run: ./gradlew clean build shadowJar publish

